export default [
    {
      "id": 1,
      "username": "Brenda.Paucek",
      "firstName": "Brenda",
      "lastName": "Paucek",
      "email": "brenda.paucek@yahoo.com",
      "adminRights": false,
      "isGuest": false,
    },
    {
      "id": 2,
      "username": "Sunny.DuBuque9",
      "firstName": "Sunny",
      "lastName": "DuBuque",
      "email": "sunny16@hotmail.com",
      "adminRights": false,
      "isGuest": false,
    },
    {
      "id": 3,
      "username": "Jessyca.Crona",
      "firstName": "Jessyca",
      "lastName": "Crona",
      "email": "jessyca99@yahoo.com",
      "adminRights": false,
      "isGuest": false,
    },
    {
      "id": 4,
      "username": "Laisha.Schulist38",
      "firstName": "Laisha",
      "lastName": "Schulist",
      "email": "laisha86@yahoo.com",
      "adminRights": false,
      "isGuest": false,
    },
    {
      "id": 5,
      "username": "Hershel_Windler48",
      "firstName": "Hershel",
      "lastName": "Windler",
      "email": "hershel3@hotmail.com",
      "adminRights": false,
      "isGuest": false,
    },
    {
      "id": 6,
      "username": "Jerod_Deckow37",
      "firstName": "Jerod",
      "lastName": "Deckow",
      "email": "jerod49@yahoo.com",
      "adminRights": false,
      "isGuest": false,
    },
    {
      "id": 7,
      "username": "Guy.Wyman",
      "firstName": "Guy",
      "lastName": "Wyman",
      "email": "guy.wyman@gmail.com",
      "creditCardCVV": 284,
      "adminRights": false,
      "isGuest": false,
    },
    {
      "id": 8,
      "username": "Bettye7",
      "firstName": "Bettye",
      "lastName": "Ferry",
      "email": "bettye_ferry36@gmail.com",
      "adminRights": false,
      "isGuest": false,
    },
    {
      "id": 9,
      "username": "Greg5",
      "firstName": "Greg",
      "lastName": "Klein",
      "email": "greg.klein6@gmail.com",
      "adminRights": false,
      "isGuest": false,
    },
]